### PR TITLE
changed password validation

### PR DESCRIPTION
**Pull request by DmitrySolyannik**

### CODE REVIEW

**Review by robtweed — COMMENTED** [review]
As far as I'm aware, a valid password should be at least 10 characters long, including upper & lower case characters, numerics or punctuation.  I think the new regex is exactly 10 numeric characters?

**Comment by DmitrySolyannik** [comment]
@robtweed , Sorry my mistake , I've already updated my PR , added possibility to use more then 10 digits

**Comment by robtweed** [comment]
You say 10 or more digits - do you mean alphanumeric characters or just numeric digits?  It should be alphanumerics

**Comment by robtweed** [comment]
Sorry - 10 or more alphanumerics and punctuation characters

**Comment by DmitrySolyannik** [comment]
Hello @robtweed , I've added changes for regex , could you please check it

**Comment by tony-shannon** [comment]
thanks @DmitrySolyannik can you confirm which repo this is PR is aimed at?
this is the older version of QewdCourier, see the QewdUp version here;
https://github.com/QEWD-Courier/QEWD-Courier-QUp

**Comment by tony-shannon** [comment]
closing this PR as was merged into latest qewdUp version of Qewd-Courier

**Pull request closed without merging**
